### ISSUE TITLE
Delete this project

### ISSUE THREAD

**Issue by igorcafe** [ruizlenato/SmudgeLord#240]
<img width="813" alt="image" src="https://github.com/ruizlenato/SmudgeLord/assets/85039990/9d8178d0-aa43-45d5-bf15-1d68bcd2c892">

**Comment by ruizlenato** [comment]
👆🏼😂😂😂😂😂😂😂👆🏼😂😂😂😂😂😂😂👆🏼😂😂😂😂😂😂😂
